defaultAirflowRepository: airflow-custom
defaultAirflowTag: "1.0.0"
airflowVersion: "2.9.3"


gitSync:
  enabled: true
  repo: ssh://git@github.com/GustavoV00/openlake.git 
  
  branch: main
  rev: HEAD
  depth: 1
  maxFailures: 0
  subPath: "airflow/dags"

  sshKeySecret: airflow-ssh-git-secret