apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: gitops
spec:
  project: default
  source:
    repoURL: "https://github.com/GustavoV00/openlake.git"
    path: infra/src/helm-charts/minio-tenant
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    name: "k8s-gvn-dev"
    namespace: "deppstorage"
    server: ""
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
