apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: warehouse
spec:
  project: default
  source:
    repoURL: "https://github.com/GustavoV00/openlake.git"
    path: infra/src/helm-charts/trino
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: "kind-demo"
    namespace: warehouse
    server: ""
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true